openapi: 3.0.0
info:
  title: Inventory Management API
  version: 1.0.0
  description: API for inventory management system
paths:
  /test:
    get:
      summary: Test endpoint
      responses:
        '200':
          description: API is working
  /debug/db-test:
    get:
      summary: Test database connection
      responses:
        '200':
          description: Database connection status
  /debug/orders-test:
    get:
      summary: Test orders database connection
      responses:
        '200':
          description: Orders database connection status
  /orders:
    get:
      summary: Get all orders
      responses:
        '200':
          description: List of all orders
  /inventory:
    get:
      summary: Get all inventory items
      responses:
        '200':
          description: List of inventory items
    post:
      summary: Create new inventory item
      responses:
        '201':
          description: Inventory item created
  /warehouses:
    get:
      summary: Get all warehouses
      responses:
        '200':
          description: List of warehouses
    post:
      summary: Create new warehouse
      responses:
        '201':
          description: Warehouse created
    options:
      summary: CORS preflight
      responses:
        '200':
          description: CORS headers
  /locations:
    get:
      summary: Get all locations
      responses:
        '200':
          description: List of locations
  /customers:
    get:
      summary: Get all customers
      responses:
        '200':
          description: List of customers
    post:
      summary: Create new customer
      responses:
        '201':
          description: Customer created