openapi: 3.0.0
info:
  title: Inventory Management API
  version: 1.0.0
  description: API for inventory management system
paths:
  /api/test:
    get:
      summary: Test endpoint
      responses:
        '200':
          description: API is working

  /api/debug/db-test:
    get:
      summary: Test database connection
      responses:
        '200':
          description: Database connection status

  /api/debug/orders-test:
    get:
      summary: Test database connection
      responses:
        '200':
          description: Orders database connection status

  /api/orders:
    get:
      summary: Get all orders
      responses:
        '200':
          description: List of all orders
    post:
      summary: Create new order
      responses:
        '201':
          description: Order created successfully

  /api/inventory:
    get:
      summary: Get all inventory items
      responses:
        '200':
          description: List of inventory items
    post:
      summary: Create new inventory item
      responses:
        '201':
          description: Inventory item created

  /api/warehouses:
    get:
      summary: Get all warehouses
      responses:
        '200':
          description: List of warehouses
    post:
      summary: Create new warehouse
      responses:
        '201':
          description: Warehouse created
    options:
      summary: CORS preflight
      responses:
        '200':
          description: CORS headers

  /api/customers:
    get:
      summary: Get all customers
      responses:
        '200':
          description: List of customers
    post:
      summary: Create new customer
      responses:
        '201':
          description: Customer created

  /api/suppliers:
    get:
      summary: Get all suppliers
      responses:
        '200':
          description: List of suppliers
    post:
      summary: Create new supplier
      responses:
        '201':
          description: Supplier created

  /api/invoices:
    get:
      summary: Get all invoices
      responses:
        '200':
          description: List of invoices
    options:
      summary: CORS preflight
      responses:
        '200':
          description: CORS headers

  /api/auth/login:
    post:
      summary: User login
      responses:
        '200':
          description: Login successful

  /api/auth/register:
    post:
      summary: User registration
      responses:
        '201':
          description: Registration successful 