services:
  - type: web
    name: trackitnow-frontend
    buildCommand: npm install && npm run build:prod
    publishDir: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://trackitnow-backend.onrender.com/api 