services:
  - type: static
    name: trackitnow-frontend
    buildCommand: |
      cd frontend
      npm install
      npm run build:prod
    publishDir: frontend/build
    nodeVersion: 16
    envVars:
      - key: REACT_APP_API_URL
        value: https://trackitnow-backend.onrender.com/api