services:
  - type: web
    name: inventory-management-api
    env: python
    rootDir: backend
    buildCommand: |
      python -m pip install --upgrade pip &&
      pip install poetry &&
      poetry install --no-dev
    startCommand: poetry run gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PWD
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false 